# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json

class Ui_MainWindow(object):
	def setupUi(self, MainWindow, data):
		self.data = data

		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(781, 461)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
		MainWindow.setSizePolicy(sizePolicy)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.listWidget = QtWidgets.QListWidget(self.centralwidget)
		self.listWidget.setGeometry(QtCore.QRect(10, 120, 641, 331))
		font = QtGui.QFont()
		font.setPointSize(12)
		self.listWidget.setFont(font)
		self.listWidget.setObjectName("listWidget")
		self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
		self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 375, 68))
		self.layoutWidget.setObjectName("layoutWidget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.IdLabel = QtWidgets.QLabel(self.layoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.IdLabel.sizePolicy().hasHeightForWidth())
		self.IdLabel.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(11)
		self.IdLabel.setFont(font)
		self.IdLabel.setObjectName("IdLabel")
		self.verticalLayout.addWidget(self.IdLabel)
		self.HumidityLabel = QtWidgets.QLabel(self.layoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.HumidityLabel.sizePolicy().hasHeightForWidth())
		self.HumidityLabel.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(11)
		self.HumidityLabel.setFont(font)
		self.HumidityLabel.setObjectName("HumidityLabel")
		self.verticalLayout.addWidget(self.HumidityLabel)
		self.CompoundLabel = QtWidgets.QLabel(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(11)
		self.CompoundLabel.setFont(font)
		self.CompoundLabel.setObjectName("CompoundLabel")
		self.verticalLayout.addWidget(self.CompoundLabel)
		self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
		self.layoutWidget1.setGeometry(QtCore.QRect(660, 120, 111, 331))
		self.layoutWidget1.setObjectName("layoutWidget1")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
		self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
		self.pushButton_3.setEnabled(False)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
		self.pushButton_3.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(13)
		font.setBold(True)
		font.setWeight(75)
		self.pushButton_3.setFont(font)
		self.pushButton_3.setObjectName("pushButton_3")
		self.verticalLayout_2.addWidget(self.pushButton_3)
		self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
		self.pushButton.setEnabled(False)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
		self.pushButton.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(13)
		font.setBold(True)
		font.setWeight(75)
		self.pushButton.setFont(font)
		self.pushButton.setObjectName("pushButton")
		self.verticalLayout_2.addWidget(self.pushButton)
		self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
		self.pushButton_2.setEnabled(False)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
		self.pushButton_2.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(13)
		font.setBold(True)
		font.setWeight(75)
		self.pushButton_2.setFont(font)
		self.pushButton_2.setObjectName("pushButton_2")
		self.verticalLayout_2.addWidget(self.pushButton_2)
		self.AddButton = QtWidgets.QPushButton(self.layoutWidget1)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.AddButton.sizePolicy().hasHeightForWidth())
		self.AddButton.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(13)
		font.setBold(True)
		font.setWeight(75)
		self.AddButton.setFont(font)
		self.AddButton.setStyleSheet("")
		self.AddButton.setObjectName("AddButton")
		self.verticalLayout_2.addWidget(self.AddButton)
		self.editButton = QtWidgets.QPushButton(self.layoutWidget1)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.editButton.sizePolicy().hasHeightForWidth())
		self.editButton.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(13)
		font.setBold(True)
		font.setWeight(75)
		self.editButton.setFont(font)
		self.editButton.setStyleSheet("")
		self.editButton.setObjectName("editButton")
		self.verticalLayout_2.addWidget(self.editButton)
		self.deleteButton = QtWidgets.QPushButton(self.layoutWidget1)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
		self.deleteButton.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(13)
		font.setBold(True)
		font.setWeight(75)
		self.deleteButton.setFont(font)
		self.deleteButton.setStyleSheet("")
		self.deleteButton.setObjectName("deleteButton")
		self.verticalLayout_2.addWidget(self.deleteButton)
		MainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

		self.pushButton.setEnabled(False)
		self.pushButton_2.setEnabled(False)
		self.pushButton_3.setEnabled(False)
		self.editButton.setEnabled(False)
		self.deleteButton.setEnabled(False)

		self.AddButton.clicked.connect(lambda: self.add_button())
		self.listWidget.itemClicked.connect(self.itemClicked_event)
		self.pushButton.clicked.connect(lambda: self.water_button())
		self.pushButton_2.clicked.connect(lambda: self.light_button())
		self.deleteButton.clicked.connect(lambda: self.delete())
		self.editButton.clicked.connect(lambda: self.edit())
		self.pushButton_3.clicked.connect(lambda: self.open_settings())
		self.listWidget.currentItemChanged.connect(lambda: self.list_chenged())

		self.refresh_list()

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "Список контроллеров"))
		self.IdLabel.setText(_translate("MainWindow", "Id: "))
		self.HumidityLabel.setText(_translate("MainWindow", "Влажность почвы: "))
		self.CompoundLabel.setText(_translate("MainWindow", "Минеральный состав почвы: "))
		self.pushButton_3.setText(_translate("MainWindow", "Настройки"))
		self.pushButton.setText(_translate("MainWindow", "Полив"))
		self.pushButton_2.setText(_translate("MainWindow", "Свет"))
		self.AddButton.setText(_translate("MainWindow", "Добавить"))
		self.editButton.setText(_translate("MainWindow", "Изменить"))
		self.deleteButton.setText(_translate("MainWindow", "Удалить"))
	
	def list_chenged(self):
		self.pushButton.setEnabled(False)
		self.pushButton_2.setEnabled(False)
		self.pushButton_3.setEnabled(False)
		self.editButton.setEnabled(False)
		self.deleteButton.setEnabled(False)
		
		self.pushButton.setStyleSheet('')
		self.pushButton_2.setStyleSheet('')

		self.select_item = ''

	def refresh_list(self):
		pass
	
	def water_button(self):
		pass

	def itemClicked_event(self, item):
		pass

	def add_button(self):
		pass

	def light_button(self):
		pass

	def delete(self):
		pass
	
	def edit(self):
		pass

	def open_settings(self):
		pass

if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
