# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
	def setupUi(self, widget):
		widget.setObjectName("widget")
		widget.resize(400, 300)
		self.AddButton = QtWidgets.QPushButton(widget)
		self.AddButton.setGeometry(QtCore.QRect(270, 260, 121, 31))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.AddButton.sizePolicy().hasHeightForWidth())
		self.AddButton.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(13)
		self.AddButton.setFont(font)
		self.AddButton.setObjectName("AddButton")
		self.CancelButton = QtWidgets.QPushButton(widget)
		self.CancelButton.setGeometry(QtCore.QRect(10, 260, 121, 31))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.CancelButton.sizePolicy().hasHeightForWidth())
		self.CancelButton.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(13)
		self.CancelButton.setFont(font)
		self.CancelButton.setObjectName("CancelButton")
		self.layoutWidget_2 = QtWidgets.QWidget(widget)
		self.layoutWidget_2.setGeometry(QtCore.QRect(20, 174, 361, 59))
		self.layoutWidget_2.setObjectName("layoutWidget_2")
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
		self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.passLabel = QtWidgets.QLabel(self.layoutWidget_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.passLabel.sizePolicy().hasHeightForWidth())
		self.passLabel.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.passLabel.setFont(font)
		self.passLabel.setObjectName("passLabel")
		self.horizontalLayout_3.addWidget(self.passLabel)
		self.passLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(12)
		self.passLineEdit.setFont(font)
		self.passLineEdit.setObjectName("passLineEdit")
		self.horizontalLayout_3.addWidget(self.passLineEdit)
		self.layoutWidget = QtWidgets.QWidget(widget)
		self.layoutWidget.setGeometry(QtCore.QRect(20, 45, 361, 59))
		self.layoutWidget.setObjectName("layoutWidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.nameLabel = QtWidgets.QLabel(self.layoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
		self.nameLabel.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.nameLabel.setFont(font)
		self.nameLabel.setObjectName("nameLabel")
		self.horizontalLayout.addWidget(self.nameLabel)
		self.nameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
		font = QtGui.QFont()
		font.setPointSize(12)
		self.nameLineEdit.setFont(font)
		self.nameLineEdit.setObjectName("nameLineEdit")
		self.horizontalLayout.addWidget(self.nameLineEdit)
		self.layoutWidget_3 = QtWidgets.QWidget(widget)
		self.layoutWidget_3.setGeometry(QtCore.QRect(20, 110, 361, 58))
		self.layoutWidget_3.setObjectName("layoutWidget_3")
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
		self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.IDLabel = QtWidgets.QLabel(self.layoutWidget_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.IDLabel.sizePolicy().hasHeightForWidth())
		self.IDLabel.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.IDLabel.setFont(font)
		self.IDLabel.setObjectName("IDLabel")
		self.horizontalLayout_2.addWidget(self.IDLabel)
		self.IDLineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
		font = QtGui.QFont()
		font.setPointSize(12)
		self.IDLineEdit.setFont(font)
		self.IDLineEdit.setObjectName("IDLineEdit")
		self.horizontalLayout_2.addWidget(self.IDLineEdit)

		self.retranslateUi(widget)
		QtCore.QMetaObject.connectSlotsByName(widget)

		self.CancelButton.clicked.connect(lambda: self.cancel())
		self.AddButton.clicked.connect(lambda: self.add())

	def retranslateUi(self, widget):
		_translate = QtCore.QCoreApplication.translate
		widget.setWindowTitle(_translate("widget", "Добавить контроллер"))
		self.AddButton.setText(_translate("widget", "Добавить"))
		self.CancelButton.setText(_translate("widget", "Отмена"))
		self.passLabel.setText(_translate("widget", "Пароль"))
		self.nameLabel.setText(_translate("widget", "Имя"))
		self.IDLabel.setText(_translate("widget", "ID"))
	
	def cancel(self):
		pass

	def add(self):
		pass


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	widget = QtWidgets.QWidget()
	ui = Ui_widget()
	ui.setupUi(widget)
	widget.show()
	sys.exit(app.exec_())
